import { build } from 'esbuild';
import { appendFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const directory = path.dirname(fileURLToPath(import.meta.url));
const assets = path.resolve(directory, '../assets');
await mkdir(assets, { recursive: true });
const result = await build({
  absWorkingDir: directory,
  entryPoints: ['editor.js'],
  outfile: path.join(assets, 'markdown-editor.js'),
  bundle: true,
  format: 'iife',
  target: ['es2022'],
  minify: true,
  legalComments: 'eof',
  metafile: true,
  banner: { js: '// Generated by npm run build in internal/web/editor. See markdown-editor.LICENSE.txt.' },
});

const packages = new Set();
for (const input of Object.keys(result.metafile.inputs)) {
  const match = input.match(/node_modules\/((?:@[^/]+\/)?[^/]+)\//);
  if (match) packages.add(match[1]);
}
const notices = [];
for (const name of [...packages].sort()) {
  const root = path.join(directory, 'node_modules', name);
  const metadata = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
  let license;
  for (const filename of ['LICENSE', 'LICENSE.txt', 'LICENSE.md']) {
    try {
      license = await readFile(path.join(root, filename), 'utf8');
      break;
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
  }
  if (!license) throw new Error('Missing license for bundled package ' + name);
  notices.push(`${name} ${metadata.version} (${metadata.license})\n\n${license.trim()}\n`);
}
const licenses = notices.join('\n---\n\n');
await writeFile(path.join(assets, 'markdown-editor.LICENSE.txt'), licenses);
// Carry the full notices with the shipped script (and therefore the Go binary).
await appendFile(path.join(assets, 'markdown-editor.js'), '\n/*\n' + licenses.replaceAll('*/', '* /') + '\n*/\n');
console.log('Built embedded Markdown editor and third-party license notices.');
